//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19432541_HoangThiToThuy_Client.tothuy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSinhVien", Namespace="http://tempuri.org/", ItemName="sinhVien")]
    [System.SerializableAttribute()]
    public class ArrayOfSinhVien : System.Collections.Generic.List<_19432541_HoangThiToThuy_Client.tothuy.sinhVien> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sinhVien", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class sinhVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string khoaField;
        
        private int tuoiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ma {
            get {
                return this.maField;
            }
            set {
                if ((object.ReferenceEquals(this.maField, value) != true)) {
                    this.maField = value;
                    this.RaisePropertyChanged("ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ten {
            get {
                return this.tenField;
            }
            set {
                if ((object.ReferenceEquals(this.tenField, value) != true)) {
                    this.tenField = value;
                    this.RaisePropertyChanged("ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lop {
            get {
                return this.lopField;
            }
            set {
                if ((object.ReferenceEquals(this.lopField, value) != true)) {
                    this.lopField = value;
                    this.RaisePropertyChanged("lop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string khoa {
            get {
                return this.khoaField;
            }
            set {
                if ((object.ReferenceEquals(this.khoaField, value) != true)) {
                    this.khoaField = value;
                    this.RaisePropertyChanged("khoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int tuoi {
            get {
                return this.tuoiField;
            }
            set {
                if ((this.tuoiField.Equals(value) != true)) {
                    this.tuoiField = value;
                    this.RaisePropertyChanged("tuoi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tothuy.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/add", ReplyAction="*")]
        _19432541_HoangThiToThuy_Client.tothuy.addResponse add(_19432541_HoangThiToThuy_Client.tothuy.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/add", ReplyAction="*")]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.addResponse> addAsync(_19432541_HoangThiToThuy_Client.tothuy.addRequest request);
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStudent", ReplyAction="*")]
        _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentResponse UpdateStudent(_19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.UpdateStudentResponse> UpdateStudentAsync(_19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequest request);
        
        // CODEGEN: Generating message contract since element name listDSResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listDS", ReplyAction="*")]
        _19432541_HoangThiToThuy_Client.tothuy.listDSResponse listDS(_19432541_HoangThiToThuy_Client.tothuy.listDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listDS", ReplyAction="*")]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.listDSResponse> listDSAsync(_19432541_HoangThiToThuy_Client.tothuy.listDSRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ds_id", ReplyAction="*")]
        _19432541_HoangThiToThuy_Client.tothuy.ds_idResponse ds_id(_19432541_HoangThiToThuy_Client.tothuy.ds_idRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ds_id", ReplyAction="*")]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.ds_idResponse> ds_idAsync(_19432541_HoangThiToThuy_Client.tothuy.ds_idRequest request);
        
        // CODEGEN: Generating message contract since element name ten from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ds_theoTen", ReplyAction="*")]
        _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenResponse ds_theoTen(_19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ds_theoTen", ReplyAction="*")]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.ds_theoTenResponse> ds_theoTenAsync(_19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/xoaThanhVien", ReplyAction="*")]
        _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienResponse xoaThanhVien(_19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/xoaThanhVien", ReplyAction="*")]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienResponse> xoaThanhVienAsync(_19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="add", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.addRequestBody Body;
        
        public addRequest() {
        }
        
        public addRequest(_19432541_HoangThiToThuy_Client.tothuy.addRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ten;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lop;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string khoa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int tuoi;
        
        public addRequestBody() {
        }
        
        public addRequestBody(string ma, string ten, string lop, string khoa, int tuoi) {
            this.ma = ma;
            this.ten = ten;
            this.lop = lop;
            this.khoa = khoa;
            this.tuoi = tuoi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addResponse", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.addResponseBody Body;
        
        public addResponse() {
        }
        
        public addResponse(_19432541_HoangThiToThuy_Client.tothuy.addResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addResult;
        
        public addResponseBody() {
        }
        
        public addResponseBody(string addResult) {
            this.addResult = addResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudent", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequestBody Body;
        
        public UpdateStudentRequest() {
        }
        
        public UpdateStudentRequest(_19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ten;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lop;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string khoa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int tuoi;
        
        public UpdateStudentRequestBody() {
        }
        
        public UpdateStudentRequestBody(string ma, string ten, string lop, string khoa, int tuoi) {
            this.ma = ma;
            this.ten = ten;
            this.lop = lop;
            this.khoa = khoa;
            this.tuoi = tuoi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentResponseBody Body;
        
        public UpdateStudentResponse() {
        }
        
        public UpdateStudentResponse(_19432541_HoangThiToThuy_Client.tothuy.UpdateStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateStudentResult;
        
        public UpdateStudentResponseBody() {
        }
        
        public UpdateStudentResponseBody(bool UpdateStudentResult) {
            this.UpdateStudentResult = UpdateStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listDSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listDS", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.listDSRequestBody Body;
        
        public listDSRequest() {
        }
        
        public listDSRequest(_19432541_HoangThiToThuy_Client.tothuy.listDSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listDSRequestBody {
        
        public listDSRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listDSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listDSResponse", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.listDSResponseBody Body;
        
        public listDSResponse() {
        }
        
        public listDSResponse(_19432541_HoangThiToThuy_Client.tothuy.listDSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listDSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.ArrayOfSinhVien listDSResult;
        
        public listDSResponseBody() {
        }
        
        public listDSResponseBody(_19432541_HoangThiToThuy_Client.tothuy.ArrayOfSinhVien listDSResult) {
            this.listDSResult = listDSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_id", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.ds_idRequestBody Body;
        
        public ds_idRequest() {
        }
        
        public ds_idRequest(_19432541_HoangThiToThuy_Client.tothuy.ds_idRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ds_idRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public ds_idRequestBody() {
        }
        
        public ds_idRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_idResponse", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.ds_idResponseBody Body;
        
        public ds_idResponse() {
        }
        
        public ds_idResponse(_19432541_HoangThiToThuy_Client.tothuy.ds_idResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ds_idResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.sinhVien ds_idResult;
        
        public ds_idResponseBody() {
        }
        
        public ds_idResponseBody(_19432541_HoangThiToThuy_Client.tothuy.sinhVien ds_idResult) {
            this.ds_idResult = ds_idResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_theoTenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_theoTen", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequestBody Body;
        
        public ds_theoTenRequest() {
        }
        
        public ds_theoTenRequest(_19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ds_theoTenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ten;
        
        public ds_theoTenRequestBody() {
        }
        
        public ds_theoTenRequestBody(string ten) {
            this.ten = ten;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_theoTenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_theoTenResponse", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenResponseBody Body;
        
        public ds_theoTenResponse() {
        }
        
        public ds_theoTenResponse(_19432541_HoangThiToThuy_Client.tothuy.ds_theoTenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ds_theoTenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.ArrayOfSinhVien ds_theoTenResult;
        
        public ds_theoTenResponseBody() {
        }
        
        public ds_theoTenResponseBody(_19432541_HoangThiToThuy_Client.tothuy.ArrayOfSinhVien ds_theoTenResult) {
            this.ds_theoTenResult = ds_theoTenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class xoaThanhVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="xoaThanhVien", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequestBody Body;
        
        public xoaThanhVienRequest() {
        }
        
        public xoaThanhVienRequest(_19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class xoaThanhVienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public xoaThanhVienRequestBody() {
        }
        
        public xoaThanhVienRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class xoaThanhVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="xoaThanhVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienResponseBody Body;
        
        public xoaThanhVienResponse() {
        }
        
        public xoaThanhVienResponse(_19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class xoaThanhVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool xoaThanhVienResult;
        
        public xoaThanhVienResponseBody() {
        }
        
        public xoaThanhVienResponseBody(bool xoaThanhVienResult) {
            this.xoaThanhVienResult = xoaThanhVienResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap>, _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _19432541_HoangThiToThuy_Client.tothuy.addResponse _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.add(_19432541_HoangThiToThuy_Client.tothuy.addRequest request) {
            return base.Channel.add(request);
        }
        
        public string add(string ma, string ten, string lop, string khoa, int tuoi) {
            _19432541_HoangThiToThuy_Client.tothuy.addRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.addRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.addRequestBody();
            inValue.Body.ma = ma;
            inValue.Body.ten = ten;
            inValue.Body.lop = lop;
            inValue.Body.khoa = khoa;
            inValue.Body.tuoi = tuoi;
            _19432541_HoangThiToThuy_Client.tothuy.addResponse retVal = ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).add(inValue);
            return retVal.Body.addResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.addResponse> _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.addAsync(_19432541_HoangThiToThuy_Client.tothuy.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.addResponse> addAsync(string ma, string ten, string lop, string khoa, int tuoi) {
            _19432541_HoangThiToThuy_Client.tothuy.addRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.addRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.addRequestBody();
            inValue.Body.ma = ma;
            inValue.Body.ten = ten;
            inValue.Body.lop = lop;
            inValue.Body.khoa = khoa;
            inValue.Body.tuoi = tuoi;
            return ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentResponse _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.UpdateStudent(_19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequest request) {
            return base.Channel.UpdateStudent(request);
        }
        
        public bool UpdateStudent(string ma, string ten, string lop, string khoa, int tuoi) {
            _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequestBody();
            inValue.Body.ma = ma;
            inValue.Body.ten = ten;
            inValue.Body.lop = lop;
            inValue.Body.khoa = khoa;
            inValue.Body.tuoi = tuoi;
            _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentResponse retVal = ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).UpdateStudent(inValue);
            return retVal.Body.UpdateStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.UpdateStudentResponse> _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.UpdateStudentAsync(_19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequest request) {
            return base.Channel.UpdateStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.UpdateStudentResponse> UpdateStudentAsync(string ma, string ten, string lop, string khoa, int tuoi) {
            _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.UpdateStudentRequestBody();
            inValue.Body.ma = ma;
            inValue.Body.ten = ten;
            inValue.Body.lop = lop;
            inValue.Body.khoa = khoa;
            inValue.Body.tuoi = tuoi;
            return ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).UpdateStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _19432541_HoangThiToThuy_Client.tothuy.listDSResponse _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.listDS(_19432541_HoangThiToThuy_Client.tothuy.listDSRequest request) {
            return base.Channel.listDS(request);
        }
        
        public _19432541_HoangThiToThuy_Client.tothuy.ArrayOfSinhVien listDS() {
            _19432541_HoangThiToThuy_Client.tothuy.listDSRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.listDSRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.listDSRequestBody();
            _19432541_HoangThiToThuy_Client.tothuy.listDSResponse retVal = ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).listDS(inValue);
            return retVal.Body.listDSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.listDSResponse> _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.listDSAsync(_19432541_HoangThiToThuy_Client.tothuy.listDSRequest request) {
            return base.Channel.listDSAsync(request);
        }
        
        public System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.listDSResponse> listDSAsync() {
            _19432541_HoangThiToThuy_Client.tothuy.listDSRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.listDSRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.listDSRequestBody();
            return ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).listDSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _19432541_HoangThiToThuy_Client.tothuy.ds_idResponse _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.ds_id(_19432541_HoangThiToThuy_Client.tothuy.ds_idRequest request) {
            return base.Channel.ds_id(request);
        }
        
        public _19432541_HoangThiToThuy_Client.tothuy.sinhVien ds_id(string id) {
            _19432541_HoangThiToThuy_Client.tothuy.ds_idRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.ds_idRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.ds_idRequestBody();
            inValue.Body.id = id;
            _19432541_HoangThiToThuy_Client.tothuy.ds_idResponse retVal = ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).ds_id(inValue);
            return retVal.Body.ds_idResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.ds_idResponse> _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.ds_idAsync(_19432541_HoangThiToThuy_Client.tothuy.ds_idRequest request) {
            return base.Channel.ds_idAsync(request);
        }
        
        public System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.ds_idResponse> ds_idAsync(string id) {
            _19432541_HoangThiToThuy_Client.tothuy.ds_idRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.ds_idRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.ds_idRequestBody();
            inValue.Body.id = id;
            return ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).ds_idAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenResponse _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.ds_theoTen(_19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequest request) {
            return base.Channel.ds_theoTen(request);
        }
        
        public _19432541_HoangThiToThuy_Client.tothuy.ArrayOfSinhVien ds_theoTen(string ten) {
            _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequestBody();
            inValue.Body.ten = ten;
            _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenResponse retVal = ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).ds_theoTen(inValue);
            return retVal.Body.ds_theoTenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.ds_theoTenResponse> _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.ds_theoTenAsync(_19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequest request) {
            return base.Channel.ds_theoTenAsync(request);
        }
        
        public System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.ds_theoTenResponse> ds_theoTenAsync(string ten) {
            _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.ds_theoTenRequestBody();
            inValue.Body.ten = ten;
            return ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).ds_theoTenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienResponse _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.xoaThanhVien(_19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequest request) {
            return base.Channel.xoaThanhVien(request);
        }
        
        public bool xoaThanhVien(string id) {
            _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequestBody();
            inValue.Body.id = id;
            _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienResponse retVal = ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).xoaThanhVien(inValue);
            return retVal.Body.xoaThanhVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienResponse> _19432541_HoangThiToThuy_Client.tothuy.WebService1Soap.xoaThanhVienAsync(_19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequest request) {
            return base.Channel.xoaThanhVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<_19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienResponse> xoaThanhVienAsync(string id) {
            _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequest inValue = new _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequest();
            inValue.Body = new _19432541_HoangThiToThuy_Client.tothuy.xoaThanhVienRequestBody();
            inValue.Body.id = id;
            return ((_19432541_HoangThiToThuy_Client.tothuy.WebService1Soap)(this)).xoaThanhVienAsync(inValue);
        }
    }
}
