//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookClient.calcref {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class1", Namespace="http://nhopro1.org/")]
    [System.SerializableAttribute()]
    public partial class Class1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string publisherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string author {
            get {
                return this.authorField;
            }
            set {
                if ((object.ReferenceEquals(this.authorField, value) != true)) {
                    this.authorField = value;
                    this.RaisePropertyChanged("author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string price {
            get {
                return this.priceField;
            }
            set {
                if ((object.ReferenceEquals(this.priceField, value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string publisher {
            get {
                return this.publisherField;
            }
            set {
                if ((object.ReferenceEquals(this.publisherField, value) != true)) {
                    this.publisherField = value;
                    this.RaisePropertyChanged("publisher");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nhopro1.org/", ConfigurationName="calcref.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name id from namespace http://nhopro1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/add", ReplyAction="*")]
        BookClient.calcref.addResponse add(BookClient.calcref.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/add", ReplyAction="*")]
        System.Threading.Tasks.Task<BookClient.calcref.addResponse> addAsync(BookClient.calcref.addRequest request);
        
        // CODEGEN: Generating message contract since element name dsResult from namespace http://nhopro1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/ds", ReplyAction="*")]
        BookClient.calcref.dsResponse ds(BookClient.calcref.dsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/ds", ReplyAction="*")]
        System.Threading.Tasks.Task<BookClient.calcref.dsResponse> dsAsync(BookClient.calcref.dsRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://nhopro1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/ds_id", ReplyAction="*")]
        BookClient.calcref.ds_idResponse ds_id(BookClient.calcref.ds_idRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/ds_id", ReplyAction="*")]
        System.Threading.Tasks.Task<BookClient.calcref.ds_idResponse> ds_idAsync(BookClient.calcref.ds_idRequest request);
        
        // CODEGEN: Generating message contract since element name author from namespace http://nhopro1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/ds_author", ReplyAction="*")]
        BookClient.calcref.ds_authorResponse ds_author(BookClient.calcref.ds_authorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/ds_author", ReplyAction="*")]
        System.Threading.Tasks.Task<BookClient.calcref.ds_authorResponse> ds_authorAsync(BookClient.calcref.ds_authorRequest request);
        
        // CODEGEN: Generating message contract since element name pub from namespace http://nhopro1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/ds_published", ReplyAction="*")]
        BookClient.calcref.ds_publishedResponse ds_published(BookClient.calcref.ds_publishedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/ds_published", ReplyAction="*")]
        System.Threading.Tasks.Task<BookClient.calcref.ds_publishedResponse> ds_publishedAsync(BookClient.calcref.ds_publishedRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://nhopro1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/remove", ReplyAction="*")]
        BookClient.calcref.removeResponse remove(BookClient.calcref.removeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nhopro1.org/remove", ReplyAction="*")]
        System.Threading.Tasks.Task<BookClient.calcref.removeResponse> removeAsync(BookClient.calcref.removeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="add", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.addRequestBody Body;
        
        public addRequest() {
        }
        
        public addRequest(BookClient.calcref.addRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class addRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string publisher;
        
        public addRequestBody() {
        }
        
        public addRequestBody(string id, string title, string author, string price, string publisher) {
            this.id = id;
            this.title = title;
            this.author = author;
            this.price = price;
            this.publisher = publisher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addResponse", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.addResponseBody Body;
        
        public addResponse() {
        }
        
        public addResponse(BookClient.calcref.addResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class addResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addResult;
        
        public addResponseBody() {
        }
        
        public addResponseBody(string addResult) {
            this.addResult = addResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.dsRequestBody Body;
        
        public dsRequest() {
        }
        
        public dsRequest(BookClient.calcref.dsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class dsRequestBody {
        
        public dsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dsResponse", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.dsResponseBody Body;
        
        public dsResponse() {
        }
        
        public dsResponse(BookClient.calcref.dsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class dsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookClient.calcref.Class1[] dsResult;
        
        public dsResponseBody() {
        }
        
        public dsResponseBody(BookClient.calcref.Class1[] dsResult) {
            this.dsResult = dsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_id", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.ds_idRequestBody Body;
        
        public ds_idRequest() {
        }
        
        public ds_idRequest(BookClient.calcref.ds_idRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class ds_idRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public ds_idRequestBody() {
        }
        
        public ds_idRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_idResponse", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.ds_idResponseBody Body;
        
        public ds_idResponse() {
        }
        
        public ds_idResponse(BookClient.calcref.ds_idResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class ds_idResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookClient.calcref.Class1 ds_idResult;
        
        public ds_idResponseBody() {
        }
        
        public ds_idResponseBody(BookClient.calcref.Class1 ds_idResult) {
            this.ds_idResult = ds_idResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_authorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_author", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.ds_authorRequestBody Body;
        
        public ds_authorRequest() {
        }
        
        public ds_authorRequest(BookClient.calcref.ds_authorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class ds_authorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string author;
        
        public ds_authorRequestBody() {
        }
        
        public ds_authorRequestBody(string author) {
            this.author = author;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_authorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_authorResponse", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.ds_authorResponseBody Body;
        
        public ds_authorResponse() {
        }
        
        public ds_authorResponse(BookClient.calcref.ds_authorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class ds_authorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookClient.calcref.Class1[] ds_authorResult;
        
        public ds_authorResponseBody() {
        }
        
        public ds_authorResponseBody(BookClient.calcref.Class1[] ds_authorResult) {
            this.ds_authorResult = ds_authorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_publishedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_published", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.ds_publishedRequestBody Body;
        
        public ds_publishedRequest() {
        }
        
        public ds_publishedRequest(BookClient.calcref.ds_publishedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class ds_publishedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pub;
        
        public ds_publishedRequestBody() {
        }
        
        public ds_publishedRequestBody(string pub) {
            this.pub = pub;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ds_publishedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ds_publishedResponse", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.ds_publishedResponseBody Body;
        
        public ds_publishedResponse() {
        }
        
        public ds_publishedResponse(BookClient.calcref.ds_publishedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class ds_publishedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookClient.calcref.Class1[] ds_publishedResult;
        
        public ds_publishedResponseBody() {
        }
        
        public ds_publishedResponseBody(BookClient.calcref.Class1[] ds_publishedResult) {
            this.ds_publishedResult = ds_publishedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="remove", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.removeRequestBody Body;
        
        public removeRequest() {
        }
        
        public removeRequest(BookClient.calcref.removeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class removeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public removeRequestBody() {
        }
        
        public removeRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeResponse", Namespace="http://nhopro1.org/", Order=0)]
        public BookClient.calcref.removeResponseBody Body;
        
        public removeResponse() {
        }
        
        public removeResponse(BookClient.calcref.removeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nhopro1.org/")]
    public partial class removeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookClient.calcref.Class1[] removeResult;
        
        public removeResponseBody() {
        }
        
        public removeResponseBody(BookClient.calcref.Class1[] removeResult) {
            this.removeResult = removeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : BookClient.calcref.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<BookClient.calcref.WebService1Soap>, BookClient.calcref.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookClient.calcref.addResponse BookClient.calcref.WebService1Soap.add(BookClient.calcref.addRequest request) {
            return base.Channel.add(request);
        }
        
        public string add(string id, string title, string author, string price, string publisher) {
            BookClient.calcref.addRequest inValue = new BookClient.calcref.addRequest();
            inValue.Body = new BookClient.calcref.addRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.price = price;
            inValue.Body.publisher = publisher;
            BookClient.calcref.addResponse retVal = ((BookClient.calcref.WebService1Soap)(this)).add(inValue);
            return retVal.Body.addResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookClient.calcref.addResponse> BookClient.calcref.WebService1Soap.addAsync(BookClient.calcref.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookClient.calcref.addResponse> addAsync(string id, string title, string author, string price, string publisher) {
            BookClient.calcref.addRequest inValue = new BookClient.calcref.addRequest();
            inValue.Body = new BookClient.calcref.addRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.price = price;
            inValue.Body.publisher = publisher;
            return ((BookClient.calcref.WebService1Soap)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookClient.calcref.dsResponse BookClient.calcref.WebService1Soap.ds(BookClient.calcref.dsRequest request) {
            return base.Channel.ds(request);
        }
        
        public BookClient.calcref.Class1[] ds() {
            BookClient.calcref.dsRequest inValue = new BookClient.calcref.dsRequest();
            inValue.Body = new BookClient.calcref.dsRequestBody();
            BookClient.calcref.dsResponse retVal = ((BookClient.calcref.WebService1Soap)(this)).ds(inValue);
            return retVal.Body.dsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookClient.calcref.dsResponse> BookClient.calcref.WebService1Soap.dsAsync(BookClient.calcref.dsRequest request) {
            return base.Channel.dsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookClient.calcref.dsResponse> dsAsync() {
            BookClient.calcref.dsRequest inValue = new BookClient.calcref.dsRequest();
            inValue.Body = new BookClient.calcref.dsRequestBody();
            return ((BookClient.calcref.WebService1Soap)(this)).dsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookClient.calcref.ds_idResponse BookClient.calcref.WebService1Soap.ds_id(BookClient.calcref.ds_idRequest request) {
            return base.Channel.ds_id(request);
        }
        
        public BookClient.calcref.Class1 ds_id(string id) {
            BookClient.calcref.ds_idRequest inValue = new BookClient.calcref.ds_idRequest();
            inValue.Body = new BookClient.calcref.ds_idRequestBody();
            inValue.Body.id = id;
            BookClient.calcref.ds_idResponse retVal = ((BookClient.calcref.WebService1Soap)(this)).ds_id(inValue);
            return retVal.Body.ds_idResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookClient.calcref.ds_idResponse> BookClient.calcref.WebService1Soap.ds_idAsync(BookClient.calcref.ds_idRequest request) {
            return base.Channel.ds_idAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookClient.calcref.ds_idResponse> ds_idAsync(string id) {
            BookClient.calcref.ds_idRequest inValue = new BookClient.calcref.ds_idRequest();
            inValue.Body = new BookClient.calcref.ds_idRequestBody();
            inValue.Body.id = id;
            return ((BookClient.calcref.WebService1Soap)(this)).ds_idAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookClient.calcref.ds_authorResponse BookClient.calcref.WebService1Soap.ds_author(BookClient.calcref.ds_authorRequest request) {
            return base.Channel.ds_author(request);
        }
        
        public BookClient.calcref.Class1[] ds_author(string author) {
            BookClient.calcref.ds_authorRequest inValue = new BookClient.calcref.ds_authorRequest();
            inValue.Body = new BookClient.calcref.ds_authorRequestBody();
            inValue.Body.author = author;
            BookClient.calcref.ds_authorResponse retVal = ((BookClient.calcref.WebService1Soap)(this)).ds_author(inValue);
            return retVal.Body.ds_authorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookClient.calcref.ds_authorResponse> BookClient.calcref.WebService1Soap.ds_authorAsync(BookClient.calcref.ds_authorRequest request) {
            return base.Channel.ds_authorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookClient.calcref.ds_authorResponse> ds_authorAsync(string author) {
            BookClient.calcref.ds_authorRequest inValue = new BookClient.calcref.ds_authorRequest();
            inValue.Body = new BookClient.calcref.ds_authorRequestBody();
            inValue.Body.author = author;
            return ((BookClient.calcref.WebService1Soap)(this)).ds_authorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookClient.calcref.ds_publishedResponse BookClient.calcref.WebService1Soap.ds_published(BookClient.calcref.ds_publishedRequest request) {
            return base.Channel.ds_published(request);
        }
        
        public BookClient.calcref.Class1[] ds_published(string pub) {
            BookClient.calcref.ds_publishedRequest inValue = new BookClient.calcref.ds_publishedRequest();
            inValue.Body = new BookClient.calcref.ds_publishedRequestBody();
            inValue.Body.pub = pub;
            BookClient.calcref.ds_publishedResponse retVal = ((BookClient.calcref.WebService1Soap)(this)).ds_published(inValue);
            return retVal.Body.ds_publishedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookClient.calcref.ds_publishedResponse> BookClient.calcref.WebService1Soap.ds_publishedAsync(BookClient.calcref.ds_publishedRequest request) {
            return base.Channel.ds_publishedAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookClient.calcref.ds_publishedResponse> ds_publishedAsync(string pub) {
            BookClient.calcref.ds_publishedRequest inValue = new BookClient.calcref.ds_publishedRequest();
            inValue.Body = new BookClient.calcref.ds_publishedRequestBody();
            inValue.Body.pub = pub;
            return ((BookClient.calcref.WebService1Soap)(this)).ds_publishedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookClient.calcref.removeResponse BookClient.calcref.WebService1Soap.remove(BookClient.calcref.removeRequest request) {
            return base.Channel.remove(request);
        }
        
        public BookClient.calcref.Class1[] remove(string id) {
            BookClient.calcref.removeRequest inValue = new BookClient.calcref.removeRequest();
            inValue.Body = new BookClient.calcref.removeRequestBody();
            inValue.Body.id = id;
            BookClient.calcref.removeResponse retVal = ((BookClient.calcref.WebService1Soap)(this)).remove(inValue);
            return retVal.Body.removeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookClient.calcref.removeResponse> BookClient.calcref.WebService1Soap.removeAsync(BookClient.calcref.removeRequest request) {
            return base.Channel.removeAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookClient.calcref.removeResponse> removeAsync(string id) {
            BookClient.calcref.removeRequest inValue = new BookClient.calcref.removeRequest();
            inValue.Body = new BookClient.calcref.removeRequestBody();
            inValue.Body.id = id;
            return ((BookClient.calcref.WebService1Soap)(this)).removeAsync(inValue);
        }
    }
}
