//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsWebService_client.CalcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vovanhai.wordpress.com/", ConfigurationName="CalcRef.CalculatorWebServiceSoap")]
    public interface CalculatorWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vovanhai.wordpress.com/add", ReplyAction="*")]
        double add(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vovanhai.wordpress.com/add", ReplyAction="*")]
        System.Threading.Tasks.Task<double> addAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vovanhai.wordpress.com/sub", ReplyAction="*")]
        double sub(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vovanhai.wordpress.com/sub", ReplyAction="*")]
        System.Threading.Tasks.Task<double> subAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vovanhai.wordpress.com/product", ReplyAction="*")]
        double product(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vovanhai.wordpress.com/product", ReplyAction="*")]
        System.Threading.Tasks.Task<double> productAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vovanhai.wordpress.com/div", ReplyAction="*")]
        double div(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vovanhai.wordpress.com/div", ReplyAction="*")]
        System.Threading.Tasks.Task<double> divAsync(double a, double b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServiceSoapChannel : CsWebService_client.CalcRef.CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<CsWebService_client.CalcRef.CalculatorWebServiceSoap>, CsWebService_client.CalcRef.CalculatorWebServiceSoap {
        
        public CalculatorWebServiceSoapClient() {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double add(double a, double b) {
            return base.Channel.add(a, b);
        }
        
        public System.Threading.Tasks.Task<double> addAsync(double a, double b) {
            return base.Channel.addAsync(a, b);
        }
        
        public double sub(double a, double b) {
            return base.Channel.sub(a, b);
        }
        
        public System.Threading.Tasks.Task<double> subAsync(double a, double b) {
            return base.Channel.subAsync(a, b);
        }
        
        public double product(double a, double b) {
            return base.Channel.product(a, b);
        }
        
        public System.Threading.Tasks.Task<double> productAsync(double a, double b) {
            return base.Channel.productAsync(a, b);
        }
        
        public double div(double a, double b) {
            return base.Channel.div(a, b);
        }
        
        public System.Threading.Tasks.Task<double> divAsync(double a, double b) {
            return base.Channel.divAsync(a, b);
        }
    }
}
